apiVersion: v1
kind: Pod
metadata:
  name: openam
spec:
  containers:
  - name: openam
    image: "pandiaraja2/open70"
    
---
apiVersion: v1
kind: Service
metadata:
  name: openam
  labels:
    app: openam
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: openam
