apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: openam
build:
  artifacts:
  - image: pandiaraja2/open70
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s-app.yml
